[general]
framerate = 30
bars = 28
sleep_timer = 1

[input]
method = pipewire
source = auto

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 1000
bar_delimiter = 59
frame_delimiter = 10

[smoothing]
monstercat = 0
waves = 0
gravity = 82
noise_reduction = 75
